### ISSUE TITLE
needs upgrade to post-3.12 API

### ISSUE THREAD

**Issue by mcepl** [smathot/gedit-plugin-ipython#4]
```
Traceback (most recent call last):
  File "/home/matej/.local/share/gedit/plugins/ipython.py", line 59, in do_activate
    manager = self.window.get_ui_manager()
AttributeError: 'Window' object has no attribute 'get_ui_manager'
Traceback (most recent call last):
  File "/home/matej/.local/share/gedit/plugins/ipython.py", line 71, in do_deactivate
    manager = self.window.get_ui_manager()
AttributeError: 'Window' object has no attribute 'get_ui_manager'
```

**Comment by smathot** [comment]
Project moved to https://gitlab.com/mcepl/gedit-plugin-ipython
